# Site
name: 'Tech Munching'
description: 'Your daily tech snack'
logo: '/assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
disqus: 'techmunching'
email: 'techmunching@gmail.com'
mailchimp-list: 'https://tinyletter.com/TechMunching'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    admin:
      name:           Tech Munching
      site:           https://www.techmunching.com
      avatar:         /assets/images/logo.png
      bio:            "Hi, We are Tech Munching. We hope you love it!"
      email:          techmunching@gmail.com
      twitter:        https://twitter.com/techmunching
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: "TechMunching"
      avatar: /assets/images/logo.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

# Google Analytics
google_analytics: G-Y7HGWZX785